################################################################################
# Automatically-generated file. Do not edit!
################################################################################

INO_SRCS := 
C++M_SRCS := 
ASM_SRCS := 
O_UPPER_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
PDE_SRCS := 
CC_SRCS := 
AR_SRCS := 
C_SRCS := 
HEX_SRCS := 
CXXM_SRCS := 
CCM_DEPS := 
C_UPPER_DEPS := 
PDE_DEPS := 
CXXM_DEPS := 
C_DEPS := 
AR := 
CC_DEPS := 
AR_OBJ := 
C++_DEPS := 
LINK_OBJ := 
CXX_DEPS := 
ASM_DEPS := 
HEX := 
INO_DEPS := 
SIZEDUMMY := 
S_UPPER_DEPS := 
C++M_DEPS := 
ELF := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
core/core \
core/core/libb64 \
libraries/AceButton/src/ace_button \
libraries/Adafruit-GFX-Library \
libraries/DNSServer/src \
libraries/FS/src \
libraries/GxEPD/src/GxDEPG0097BW \
libraries/GxEPD/src/GxDEPG0150BN \
libraries/GxEPD/src/GxDEPG0213BN \
libraries/GxEPD/src/GxDEPG0266BN \
libraries/GxEPD/src/GxDEPG0290B \
libraries/GxEPD/src/GxDEPG0290R \
libraries/GxEPD/src/GxDEPG0750BN \
libraries/GxEPD/src \
libraries/GxEPD/src/GxGDE0213B1 \
libraries/GxEPD/src/GxGDE0213B72 \
libraries/GxEPD/src/GxGDE0213B72B \
libraries/GxEPD/src/GxGDEH0154D67 \
libraries/GxEPD/src/GxGDEH0213B72 \
libraries/GxEPD/src/GxGDEH0213B73 \
libraries/GxEPD/src/GxGDEH029A1 \
libraries/GxEPD/src/GxGDEM0213B74 \
libraries/GxEPD/src/GxGDEP015OC1 \
libraries/GxEPD/src/GxGDEW0102I4F \
libraries/GxEPD/src/GxGDEW0154Z04 \
libraries/GxEPD/src/GxGDEW0154Z17 \
libraries/GxEPD/src/GxGDEW0213I5F \
libraries/GxEPD/src/GxGDEW0213M21 \
libraries/GxEPD/src/GxGDEW0213Z16 \
libraries/GxEPD/src/GxGDEW026T0 \
libraries/GxEPD/src/GxGDEW027C44 \
libraries/GxEPD/src/GxGDEW027W3 \
libraries/GxEPD/src/GxGDEW029T5 \
libraries/GxEPD/src/GxGDEW029Z10 \
libraries/GxEPD/src/GxGDEW0371W7 \
libraries/GxEPD/src/GxGDEW042T2 \
libraries/GxEPD/src/GxGDEW042Z15 \
libraries/GxEPD/src/GxGDEW0583T7 \
libraries/GxEPD/src/GxGDEW075T7 \
libraries/GxEPD/src/GxGDEW075T8 \
libraries/GxEPD/src/GxGDEW075Z08 \
libraries/GxEPD/src/GxGDEW075Z09 \
libraries/GxEPD/src/GxGDGDEW0102T4 \
libraries/GxEPD/src/GxIO \
libraries/GxEPD/src/GxIO/GxIO_SPI \
libraries/GxEPD/src/GxQYEG0290BN \
libraries/GxEPD/src/GxQYEG0290RWS800 \
libraries/SD/src \
libraries/SPI/src \
libraries/Update/src \
libraries/WebServer/src \
libraries/WebServer/src/detail \
libraries/WiFi/src \
libraries/WiFiManager \
libraries/libzmanim/src \

